name = "ComputacionCientificaEnJulia"
uuid = "e1c6c738-d63f-47f7-aac3-57ae89731a92"
authors = ["Marcelo Forets <mforets@gmail.com>", "Daniel Freire Caporale <dfcaporale@gmail.com>"]
version = "0.1.0"
